### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by mx-moth** [mattdw/django-dps#6]
Could this package be uploaded to PyPI? It would make packing up apps that depend upon this package much easier :)

**Comment by mattdw** [comment]
I'm not really writing any Python at the moment, especially not full-time, so I'm not super-keen to take on the maintenance burden of that! You're welcome to upload it yourself (through a fork, if you'd like), or hit me with a pull request if the setup.py needs any changes. And credit yourself in the readme! :)

**Comment by gregplaysguitar** [comment]
My branch - https://github.com/gregplaysguitar/django-dps/ - is what we've been using here, and has had a number of updates including 1.8 support. I could take on the role primary maintainer if you like, @mattdw ?

**Comment by mattdw** [comment]
That sounds like a good idea. Do you want me to do anything with my repo, @gregplaysguitar? I could add a note, or leave nothing but a link to your repo.

@timheap are you happy to go with @gregplaysguitar's fork? Consider me out of the picture at this point, but feel free to continue this discussion here.

**Comment by mattdw** [comment]
(For context, @timheap, @gregplaysguitar wrote about half of this lib. So this should be a pretty un-risky transition.)

**Comment by gregplaysguitar** [comment]
Cool, just adding a note should be fine

**Comment by mx-moth** [comment]
Going with @gregplaysguitar's fork sounds good. I've made some modifications so that it packages up nicely, I'll send them to @gregplaysguitar's repo. Thanks!

**Comment by gregplaysguitar** [comment]
All sorted - https://pypi.python.org/pypi/django-dps/

**Comment by mattdw** [comment]
Choice!
